name: CD - Push

on:
  push:
    branches:
      - develop   # gera artefatos para QA

jobs:
  build-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout do código
        uses: actions/checkout@v4

      - name: Configurar .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.x'

      - name: Restaurar dependências
        run: dotnet restore

      - name: Build
        run: dotnet build --configuration Release --no-restore

      - name: Test (opcional)
        run: |
          if ls **/*.Tests.csproj 1> /dev/null 2>&1; then
            dotnet test --configuration Release --no-build
          else
            echo "Nenhum projeto de teste encontrado, ignorando etapa de testes."
          fi

      - name: Publish artifacts
        run: dotnet publish --configuration Release --no-build --output ./publish

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: drop
          path: ./publish

      # Exemplo de deploy opcional (ajustar para seu ambiente)
      # - name: Deploy to QA/Production
      #   run: ./scripts/deploy.sh
